apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-password-dev
  namespace: rabbitmq-dev
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: azure-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: "rabbitmq-password-dev"
    creationPolicy: Owner
  data:
    - secretKey: rabbitmq-password
      remoteRef:
        key: rabbitmq-password-dev