# Set the application name
app:

# Set the image repository and proper tag
image:
  repository: 
  tag:

# Specyify rolling Update
rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

# Specify resources limits and requests 
resources:
  limits:
    # cpu: 200m
    # memory: 512Mi
  requests:
    # cpu: 100m
    # memory: 256Mi

# Change the autoscaling depending on the environment needs
autoscaling:
  maxReplicas:
  minReplicas:
  targetCPUUtilizationPercentage:
  targetMemoryUtilizationPercentage:

# Set the environment
environment:

# Specify the hostname
hostname:

# Set the service external port and internal container port
service:
  externalPort:
  internalPort:

# Set the probe value type
  # probe:
  #   type: exec
  #   command: []
hpa:
  enabled: true


# Set the path and initial delay for readiness and liveness probe
readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 5
