app: sample-app-messaging
image:
  repository: acrsampleappneu.azurecr.io/messaging
  tag: dev

environment: dev

replicas: 1

service:
  enabled: true
  internalPort: 80
  externalPort: 80

readinessProbe:
  path: /health
  initialDelaySeconds: 10
livenessProbe:
  path: /health
  initialDelaySeconds: 15

autoscaling:
  maxReplicas: 1
  minReplicas: 1

useEnvFromSecret:
  enabled: true
  refreshInterval: 24h