apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: retoxx-dev-sso-ca
  namespace: argocd
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: azure-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: "retoxx-dev-sso-ca"
    creationPolicy: Owner
  data:
    - secretKey: retoxx-dev-sso-ca
      remoteRef:
        key: retoxx-dev-sso-ca