# TODO: affinity
# global:
#   affinity:
#     nodeAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         nodeSelectorTerms:
#         - matchExpressions:
#           - key: <key>
#             operator: In
#             values:
#               - <value>

## Argo CD Server
server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: true
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: true
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      cert-manager.io/cluster-issuer: letsencrypt
      cert-manager.io/acme-challenge-type: http01
    hosts:
      - argocd.dziedzic.me
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.dziedzic.me
    https: true

## Argo CD Redis
redis:
  enabled: true

## Config files
configs:
  repositories:
    git-sample-app-infra:
      name: sample-app-infra
      type: git
      url: https://github.com/Retoxx-dev/sample-app-infra.git
    helm-sample-app-infra:
      name: helm-sample-app-infra
      type: helm
      url: https://raw.githubusercontent.com/Retoxx-dev/sample-app-helm-repo/main