# Set the application name
app:

# Set the image repository and proper tag
image:
  repository: 
  tag:

# Specyify rolling Update
rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

# Specify resources limits and requests 
resources:
  limits:
    # cpu: 200m
    # memory: 512Mi
  requests:
    # cpu: 100m
    # memory: 256Mi

# Change the autoscaling depending on the environment needs
autoscaling:
  maxReplicas:
  minReplicas:
  targetCPUUtilizationPercentage:
  targetMemoryUtilizationPercentage:

# Set the environment
environment:

# Set the ingress config
ingress:
  enabled: false
  hostname:

# Set the service external port and internal container port
service:
  enabled: true
  externalPort:
  internalPort:

# Set the probe value type
hpa:
  enabled: true


# Set the path and initial delay for readiness and liveness probe
readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
  path: /

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 5
  path: /