loki:
  auth_enabled: false
  containerSecurityContext:
    allowPrivilegeEscalation: false
  storage:
    type: azure
    azure:
      accountName: stsampleappneulogs
      userAssignedId: e65f6118-e50e-4413-88f0-118044a5fcec
  schemaConfig:
    configs:
      - from: "2022-08-01"
        store: boltdb-shipper
        object_store: azure
        schema: v12
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    boltdb_shipper:
      shared_store: azure
      active_index_directory: /var/loki/boltdb-shipper-active
      cache_location: /var/loki/boltdb-shipper-cache
      cache_ttl: 24h
read: &commonConfig
  replicas: 3
  persistence:
    size: 10Gi
    storageClassName: default
  extraArgs:
    - -config.expand-env=true
write:
  <<: *commonConfig
backend:
  <<: *commonConfig