apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-admin-password
  namespace: pgadmin
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: azure-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: "pgadmin-admin-password"
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: pgadmin-admin-password