apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-sso
  namespace: pgadmin
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: azure-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: "pgadmin-sso"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config_local.py: |-
          AUTHENTICATION_SOURCES = ['oauth2', 'internal']
          MASTER_PASSWORD_REQUIRED = True
          OAUTH2_AUTO_CREATE_USER = True
          OAUTH2_CONFIG = [
              {
                  'OAUTH2_NAME': 'Microsoft',
                  'OAUTH2_DISPLAY_NAME': 'Microsoft',
                  'OAUTH2_CLIENT_ID': '{{ .OAUTH2_CLIENT_ID }}',
                  'OAUTH2_CLIENT_SECRET': '{{ .OAUTH2_CLIENT_SECRET }}',
                  'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/{{ .OAUTH2_TENANT_ID }}/oauth2/v2.0/token',
                  'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/{{ .OAUTH2_TENANT_ID }}/oauth2/v2.0/authorize',
                  'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
                  'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/{{ .OAUTH2_TENANT_ID }}/v2.0/.well-known/openid-configuration',
                  'OAUTH2_USERINFO_ENDPOINT': 'me',
                  'OAUTH2_SCOPE': 'User.Read email openid profile',
                  'OAUTH2_ICON': 'fa-microsoft',
                  'OAUTH2_BUTTON_COLOR': '#0000FF',
              }
          ]
  data:
    - secretKey: OAUTH2_TENANT_ID
      remoteRef:
        key: pgadmin-sso
        decodingStrategy: None
        property: OAUTH2_TENANT_ID
    - secretKey: OAUTH2_CLIENT_ID
      remoteRef:
        key: pgadmin-sso
        decodingStrategy: None
        property: OAUTH2_CLIENT_ID
    - secretKey: OAUTH2_CLIENT_SECRET
      remoteRef:
        key: pgadmin-sso
        decodingStrategy: None
        property: OAUTH2_CLIENT_SECRET