ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/acme-challenge-type: http01
  hosts:
    - host: pgadmin.dziedzic.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: pgadmin-tls
      hosts:
        - pgadmin.dziedzic.me

existingSecret: pgadmin-admin-password
secretKeys:
  pgadminPasswordKey: password

env:
  email: kacper.dziedzic@wp.pl
  enhanced_cookie_protection: "False"

extraSecretMounts:
  - name: config-local
    secret: pgadmin-sso
    subPath: config_local.py
    mountPath: "/pgadmin4/config_local.py"
    readOnly: true