ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/acme-challenge-type: http01
  hosts:
    - host: pgadmin.dziedzic.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: pgadmin-tls
      hosts:
        - pgadmin.dziedzic.me

existingSecret: pgadmin-admin-password
secretKeys:
  pgadminPasswordKey: password

serverDefinitions:
  enabled: true
  servers:
    postgresql:
      Name: "sample-app"
      Group: "Servers"
      Port: 5432
      Username: "mAiplm1druv8kmhC"
      Host: "psql-sample-app-neu.postgres.database.azure.com"
      SSLMode: "prefer"
      MaintenanceDB: "postgres"
      Shared: true
      PassFile: "/var/lib/pgadmin/storage/pgadmin/sampleapp.pgpass"

env:
  email: kacper.dziedzic@wp.pl
  enhanced_cookie_protection: "False"

extraSecretMounts:
  - name: config-local
    secret: pgadmin-sso
    subPath: config_local.py
    mountPath: "/pgadmin4/config_local.py"
    readOnly: true
  
  - name: pgpassfile
    secret: pgadmin-pgpass
    subPath: pgpassfile
    mountPath: "/var/lib/pgadmin/storage/pgadmin/file.pgpass"
    readOnly: true