app: sample-app-core
image:
  repository: acrsampleappneu.azurecr.io/core
  tag: dev

environment: dev

ingress:
  enabled: true
  hostname: api.dev.dziedzic.me

replicas: 1

service:
  enabled: true
  externalPort: 80
  internalPort: 80

readinessProbe:
  path: /health
  initialDelaySeconds: 10
livenessProbe:
  path: /health
  initialDelaySeconds: 15

autoscaling:
  maxReplicas: 1
  minReplicas: 1

useEnvFromSecret: true