apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-password-prod
  namespace: rabbitmq-prod
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: azure-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: "rabbitmq-password-prod"
    creationPolicy: Owner
  data:
    - secretKey: rabbitmq-password
      remoteRef:
        key: rabbitmq-password-prod