apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      identityId: "4276939c-9d80-4418-86f6-ef0bea94e8b8"
      vaultUrl: https://kv-sample-app-neu.vault.azure.net/