---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  sources:
    - repoURL: 'https://argoproj.github.io/argo-helm'
      targetRevision: 0.9.1
      chart: argocd-image-updater
      helm:
        valueFiles:
          - $values/argocd/helmvalues/argocd-image-updater/values.yaml
    - repoURL: 'https://github.com/Retoxx-dev/sample-app-infra.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true