---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  sources:
    - repoURL: 'https://charts.external-secrets.io/'
      targetRevision: 0.9.2
      chart: external-secrets
      helm:
        valueFiles:
          - $values/argocd/helmvalues/external-secrets/values.yaml
    - repoURL: 'https://github.com/Retoxx-dev/sample-app-infra.git'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/Retoxx-dev/sample-app-infra.git'
      targetRevision: HEAD
      path: 'argocd/helmvalues/external-secrets'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true