---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress
  sources:
    - repoURL: 'https://kubernetes.github.io/ingress-nginx'
      targetRevision: 4.7.1
      chart: ingress-nginx
      helm:
        valueFiles:
          - $values/argo-cd/helmvalues/ingress.yaml
    - repoURL: 'https://github.com/Retoxx-dev/sample-app-infra.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true