---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: system
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  #FILL_IN: repository sources
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 6.17.0
      chart: external-dns
      helm:
        valueFiles:
          - $values/k8s/argo-cd/manifests/external-dns/values.yaml
    - repoURL: 'git@bitbucket.org:thesoftwarehouse/pension-lab-infrastructure.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true