---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 6.14.1
      chart: promtail
      helm:
        valueFiles:
          - $values/argocd/helmvalues/promtail/values.yaml
    - repoURL: 'https://github.com/Retoxx-dev/sample-app-infra.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true