---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-client-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd-image-updater.argoproj.io/image-list: client=acrsampleappneu.azurecr.io/client
    argocd-image-updater.argoproj.io/client.allow-tags: regexp:^prod-[a-zA-Z0-9]*$
    argocd-image-updater.argoproj.io/client.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/client.pull-secret: ext:/scripts/acrauth.sh
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sample-app-client-prod
  source:
    repoURL: 'https://github.com/Retoxx-dev/sample-app-infra.git'
    targetRevision: HEAD
    path: helm/charts/base
    helm:
      valueFiles:
        - ../../../argocd/helmvalues/sample-app-prod/client/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true