---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-client-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd-image-updater.argoproj.io/image-list: client=acrsampleappneu.azurecr.io/client
    argocd-image-updater.argoproj.io/client.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sample-app-client-dev
  source:
    repoURL: 'acrsampleappneu.azurecr.io'
    targetRevision: 0.0.2
    chart: helm/base
    helm:
      values: |
      app: sample-app-client
      image:
        repository: acrsampleappneu.azurecr.io/client
        tag: dev
      environment: dev
      ingress:
        enabled: true
        hostname: dev.dziedzic.me
      replicas: 1
      service:
        enabled: true
        externalPort: 3000
        internalPort: 3000
      readinessProbe:
        path: /
        initialDelaySeconds: 10
      livenessProbe:
        path: /
        initialDelaySeconds: 15
      autoscaling:
        maxReplicas: 1
        minReplicas: 1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true