{{- if .Values.useEnvFromSecret.enabled  }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.app }}-{{ .Values.environment }}-env"
  namespace: "{{ .Values.app }}-{{ .Values.environment }}"
spec:
  refreshInterval: "{{ .Values.useEnvFromSecret.refreshInterval | default "1h" }}"
  secretStoreRef:
    name: azure-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.app }}-{{ .Values.environment }}-env"
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "{{ .Values.app }}-{{ .Values.environment }}-env"
      decodingStrategy: None
{{- end }}